### ISSUE TITLE
Missing documentation for attribute's modifiers

### ISSUE THREAD

**Issue by fcoulon** [gemoc/ale-lang#21]
Document usage of 'contains', 'unique', 'opposite' when declaring attributes in open class

(Section 'Feature declaration' in the reference documentation)

**Comment by pjeanjean** [comment]
The documentation is also missing a section on enumerations (they are currently managed by AQL, and the syntax is nontrivial).

**Comment by dvojtise** [comment]
The documentation is also missing a section about multiplicity modifiers. ( `1 .. *`)

I also beleive that these modifiers are not well tested ...

note that several issues comes from the misunderstanding of the use of an attribute of kind `Sequence(Foo)` instead of  `1 .. * Foo`  (ex. https://github.com/gemoc/ale-lang/issues/22 or https://github.com/gemoc/ale-lang/issues/29 or https://github.com/gemoc/ale-lang/issues/42 )
