### ISSUE TITLE
Validation of .ale file crash when .dsl file has not the same name

### ISSUE THREAD

**Issue by fcoulon** [gemoc/ale-lang#4]
Bug located here:
https://github.com/gemoc/ale-lang/blob/master/plugins/org.eclipse.emf.ecoretools.ale.xtext/src/org/eclipse/emf/ecoretools/validation/AleValidator.xtend#L41

Pb: We assume .dsl file has the same name as the validated .ale file and it raises two problems:
1- We can't have different names
2- Multiple .ale files imply multiple .dsl files

We should have a project's property storing the location of the .dsl file

**Comment by dvojtise** [comment]
what about multiple .dsl files pointing/sharing some ale file ?

note about location of dsl file : see https://github.com/eclipse/gemoc-studio-modeldebugging/issues/65

**Comment by fcoulon** [comment]
In a scenario with multiple .dsl, when you open a .ale we have to launch the validation service based on a .dsl (to collect EClasses) and for now I have no clue how to select the proper one.

That why I chose to search for a .dsl with the same name as the .ale but it is a too simple solution :)

**Comment by dvojtise** [comment]
it would still not work for scenarios with multiple dsl (ie. reuse), but maybe you should look any dsl file in the project as in most cases there is only one dsl file defined per project.

bt for this we need to fix eclipse/gemoc-studio-modeldebugging#65 first because if a .dsl file is in a java src folder it is automatically copied in the bin (or target/classes) folder too...

**Comment by dvojtise** [comment]
additionnaly, when the .dsl file is missing the reported reported is unclear

![image](https://user-images.githubusercontent.com/661468/60509993-9c3dc280-9cce-11e9-8340-455621464286.png)

test project:
[ale-lang-issue-4.zip](https://github.com/gemoc/ale-lang/files/3349848/ale-lang-issue-4.zip)
