### ISSUE TITLE
Add Switch instruction

### ISSUE THREAD

**Issue by dvojtise** [gemoc/ale-lang#41]
I have some enumeration in my language and I need to change the behaviour depending on the enum value.

How can I avoid the nested `if`?

```
if(self.operator = fcl::BinaryOperator::EQUAL){	
} else { if(self.operator = fcl::BinaryOperator::PLUS){
} else { if(self.operator = fcl::BinaryOperator::MINUS){
} else { if(self.operator = fcl::BinaryOperator::MULT){
} else {
}}}}
....
```

Can we have some `switch` instruction?

**Comment by dvojtise** [comment]
decreasing priority for a real `switch` since we now have `else if` thanks to @pjeanjean in https://github.com/gemoc/ale-lang/pull/48

**Comment by echebbi** [comment]
ALE has actually had a `switch` expression for the past three years (c8241ad):

https://github.com/gemoc/ale-lang/blob/cfa611dd4deb0c0f36ffce38fd0682e531c6afb5/tests/org.eclipse.emf.ecoretools.ale.tests/input/eval/switch.implem#L5-L14

> I discovered it by accident while documenting internal classes; https://github.com/echebbi/ale-lang-docs/pull/4 will add `switch` to ALE's documentation

At the moment `case` only allows short AQL expressions though but since `else if` are now a feature I think we can close this issue.

Please reopen only with concrete enhancement proposals for the current _switch_ expressions (e.g. support for blocks in `case`).
