### ISSUE TITLE
Conversion of Sequence into OrderedSet neither typechecked nor enforced at runtime 

### ISSUE THREAD

**Issue by dvojtise** [gemoc/ale-lang#67]
Declaring a variable as an _OrderedSet_ should not allow duplicate.

However, when the _OrderedSet_ is initialized using a _Sequence_ there is no warning or error.
thus the possible duplicate in the input sequence are maintained in the variable.

I would expect to have a warning at minimum, in order to tell the user that she should use ->asOrderedSet() 

This is actually an important issue, because the content at runtime continues to behave as a _Sequence_ and not as an _OrderedSet_ 

note: using `->select` `->collect` lambdas often leads to Sequence instead of OrderedSet so it is not easy to infer the real type of what was assigned.

with the following example:
```
behavior helloworld;

open class HelloWorld {
	String msg := 'Hello world!';
	@main
	def void main () {
		// add self 2 times + an extra element
		Sequence(helloworld::HelloWorld) aSequence := Sequence{self, self, helloworld::HelloWorld.create()};
		('### aSequence.size = '+aSequence->size()).log();
		aSequence.log();
		
		OrderedSet(helloworld::HelloWorld) anOrderedSet := aSequence; // Should raise an error in the typechecker and at runtime
		('### anOrderedSet.size = '+anOrderedSet->size()).log();
		anOrderedSet.log();
		
		anOrderedSet += self;
		('### adding duplicate in anOrderedSet:\n anOrderedSet.size = '+anOrderedSet->size()).log();
		anOrderedSet.log();
		
		OrderedSet(helloworld::HelloWorld) anOrderedSet_fixed := aSequence->asOrderedSet();
		('### adding duplicate in anOrderedSet:\n anOrderedSet_fixed.size = '+anOrderedSet_fixed->size()).log();
		anOrderedSet_fixed.log();
		
		anOrderedSet_fixed += self;
		('### adding duplicate in anOrderedSet_fixed:\n anOrderedSet_fixed.size = '+anOrderedSet_fixed->size()).log();
		anOrderedSet_fixed.log();	
	}
}
```

produce the following output:
```
Run helloworld.dsl
------------
### aSequence.size = 3
org.eclipse.emf.ecore.impl.DynamicEObjectImpl@39bcb421 (eClass: org.eclipse.emf.ecore.impl.EClassImpl@3f3f193a (name: HelloWorld) (instanceClassName: null) (abstract: false, interface: false))
org.eclipse.emf.ecore.impl.DynamicEObjectImpl@39bcb421 (eClass: org.eclipse.emf.ecore.impl.EClassImpl@3f3f193a (name: HelloWorld) (instanceClassName: null) (abstract: false, interface: false))
org.eclipse.emf.ecore.impl.DynamicEObjectImpl@1160abe1 (eClass: org.eclipse.emf.ecore.impl.EClassImpl@3f3f193a (name: HelloWorld) (instanceClassName: null) (abstract: false, interface: false))
### anOrderedSet.size = 3
org.eclipse.emf.ecore.impl.DynamicEObjectImpl@39bcb421 (eClass: org.eclipse.emf.ecore.impl.EClassImpl@3f3f193a (name: HelloWorld) (instanceClassName: null) (abstract: false, interface: false))
org.eclipse.emf.ecore.impl.DynamicEObjectImpl@39bcb421 (eClass: org.eclipse.emf.ecore.impl.EClassImpl@3f3f193a (name: HelloWorld) (instanceClassName: null) (abstract: false, interface: false))
org.eclipse.emf.ecore.impl.DynamicEObjectImpl@1160abe1 (eClass: org.eclipse.emf.ecore.impl.EClassImpl@3f3f193a (name: HelloWorld) (instanceClassName: null) (abstract: false, interface: false))
### adding duplicate in anOrderedSet:
 anOrderedSet.size = 4
org.eclipse.emf.ecore.impl.DynamicEObjectImpl@39bcb421 (eClass: org.eclipse.emf.ecore.impl.EClassImpl@3f3f193a (name: HelloWorld) (instanceClassName: null) (abstract: false, interface: false))
org.eclipse.emf.ecore.impl.DynamicEObjectImpl@39bcb421 (eClass: org.eclipse.emf.ecore.impl.EClassImpl@3f3f193a (name: HelloWorld) (instanceClassName: null) (abstract: false, interface: false))
org.eclipse.emf.ecore.impl.DynamicEObjectImpl@1160abe1 (eClass: org.eclipse.emf.ecore.impl.EClassImpl@3f3f193a (name: HelloWorld) (instanceClassName: null) (abstract: false, interface: false))
org.eclipse.emf.ecore.impl.DynamicEObjectImpl@39bcb421 (eClass: org.eclipse.emf.ecore.impl.EClassImpl@3f3f193a (name: HelloWorld) (instanceClassName: null) (abstract: false, interface: false))
### adding duplicate in anOrderedSet:
 anOrderedSet_fixed.size = 2
org.eclipse.emf.ecore.impl.DynamicEObjectImpl@39bcb421 (eClass: org.eclipse.emf.ecore.impl.EClassImpl@3f3f193a (name: HelloWorld) (instanceClassName: null) (abstract: false, interface: false))
org.eclipse.emf.ecore.impl.DynamicEObjectImpl@1160abe1 (eClass: org.eclipse.emf.ecore.impl.EClassImpl@3f3f193a (name: HelloWorld) (instanceClassName: null) (abstract: false, interface: false))
### adding duplicate in anOrderedSet_fixed:
 anOrderedSet_fixed.size = 2
org.eclipse.emf.ecore.impl.DynamicEObjectImpl@39bcb421 (eClass: org.eclipse.emf.ecore.impl.EClassImpl@3f3f193a (name: HelloWorld) (instanceClassName: null) (abstract: false, interface: false))
org.eclipse.emf.ecore.impl.DynamicEObjectImpl@1160abe1 (eClass: org.eclipse.emf.ecore.impl.EClassImpl@3f3f193a (name: HelloWorld) (instanceClassName: null) (abstract: false, interface: false))

```

where the incorrectly initialized variable has duplicate entries, and continues to add duplicate

**Comment by echebbi** [comment]
I believe we have several problems here.

### Local variables cannot be statically typed as Sets

I think that local variables are currently typed as regular Lists. In order to build the AST, the AQL type is turned into an EMF classifier as follows:

https://github.com/gemoc/ale-lang/blob/1115bcc39802de45a30b504689f6c34bfdb3d575/plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/parser/visitor/ModelBuilder.java#L585-L588

And we can see that no post-processing is done to distinguish Sets from Lists:

https://github.com/gemoc/ale-lang/blob/1115bcc39802de45a30b504689f6c34bfdb3d575/plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/parser/visitor/ModelBuilder.java#L230-L246


### The type checker converts every EMF List to a Sequence

I noticed (introduced?) this while refactoring and chose to delay the fix. This decision was also motivated by the fact that runtime features seem to have the `unique` attribute set to `true` by default (didn't take the time to investigate that though):

https://github.com/gemoc/ale-lang/blob/1115bcc39802de45a30b504689f6c34bfdb3d575/plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/validation/impl/ConvertType.java#L38-L57


### The interpreter does not support `+=` on Sets

The line `anOrderedSet_fixed += self` now leads to an error:

```
[AQL eval fail] At line 25 in helloworld\model\helloworld.ale :
Diagnostic ERROR source=interpreter code=0 Variable 'anOrderedSet_fixed' is not a list, cannot insert org.eclipse.emf.ecore.impl.DynamicEObjectImpl@1ab966b8 (eClass: org.eclipse.emf.ecore.impl.EClassImpl@60946b1a (name: HelloWorld) (instanceClassName: null) (abstract: false, interface: false)) data=[org.eclipse.acceleo.query.ast.impl.VarRefImpl@7a9aebb5 (variableName: self)]
Variable 'anOrderedSet_fixed' is not a list, cannot insert org.eclipse.emf.ecore.impl.DynamicEObjectImpl@1ab966b8 (eClass: org.eclipse.emf.ecore.impl.EClassImpl@60946b1a (name: HelloWorld) (instanceClassName: null) (abstract: false, interface: false))
```

This error message has been committed in ab923d0 and introduced by PR #69. It outlines the fact that the `+=` operator has actually no effect when used on sets:

https://github.com/gemoc/ale-lang/blob/1115bcc39802de45a30b504689f6c34bfdb3d575/plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/interpreter/MethodEvaluator.java#L239-L261

We will also have to make sure the operators work as expected on sets.

**Comment by echebbi** [comment]
As of #130 almost everything is done:

![image](https://user-images.githubusercontent.com/25926433/81205863-8de5c480-8fcb-11ea-87a7-744738241bb7.png)

The only remaining issue is to compute type validation at runtime (see also #128).
